services:
  web:
    build: .
    volumes:
      - ./app:/code/app
      - ./db_data:/code/db_data
    ports:
      - "8000:8000"
    env_file:
      - .env
    working_dir: /code/app
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python create_superuser.py &&
             python manage.py runserver 0.0.0.0:8000"
